

const store = {
    isKeyboard: false,
    searchText: '',
    currentPage: 1,
    dataBase: [
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BMTQ5NjQ0NDI3NF5BMl5BanBnXkFtZTcwNDI0MjEzMw@@._V1_SX300.jpg",
            Title: "The Pursuit of Happyness",
            Type: "movie",
            Year: "2006",
            imdbID: "tt0454921",
            rating: "8.0",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BZDAwYTlhMDEtNTg0OS00NDY2LWJjOWItNWY3YTZkM2UxYzUzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
            Title: "Léon: The Professional",
            Type: "movie",
            Year: "1994",
            imdbID: "tt0110413",
            rating: "8.5",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BMTk2MjcxNjMzN15BMl5BanBnXkFtZTgwMTE3OTEwNjE@._V1_SX300.jpg",
            Title: "Knockin' on Heaven's Door",
            Type: "movie",
            Year: "1997",
            imdbID: "tt0119472",
            rating: "8.0",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
            Title: "Pulp Fiction",
            Type: "movie",
            Year: "1994",
            imdbID: "tt0110912",
            rating: "8.9",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BMzcwYWFkYzktZjAzNC00OGY1LWI4YTgtNzc5MzVjMDVmNjY0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            Title: "A Beautiful Mind",
            Type: "movie",
            Year: "2001",
            imdbID: "tt0268978",
            rating: "8.2",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BMTAyN2JmZmEtNjAyMy00NzYwLThmY2MtYWQ3OGNhNjExMmM4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
            Title: "Lock, Stock and Two Smoking Barrels",
            Type: "movie",
            Year: "1998",
            imdbID: "tt0120735",
            rating: "8.2",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg",
            Title: "Once Upon a Time... in Hollywood",
            Type: "movie",
            Year: "2019",
            imdbID: "tt7131622",
            rating: "7.7",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            Title: "Forrest Gump",
            Type: "movie",
            Year: "1994",
            imdbID: "tt0109830",
            rating: "8.8",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SX300.jpg",
            Title: "The Intouchables",
            Type: "movie",
            Year: "2011",
            imdbID: "tt1675434",
            rating: "8.5",
        },
        {
            Poster: "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
            Title: "Schindler's List",
            Type: "movie",
            Year: "1993",
            imdbID: "tt0108052",
            rating: "8.9",
        },
    ],
    isSearch: false,
}

export default store;